### ISSUE TITLE
Implement Interface of Prototype 1

### ISSUE THREAD

**Issue by MarshallCN** [EADG6/TrainTickets#8]
**Download [Pingendo](http://pingendo.com) and use it to implement your design in HTML/CSS code**
_if u are able to use notepad++ to code your system, that's better_
- [x] Tickets Selling Page - Cary #2 
- [x] Ticket Management Page - John #3 
- [x] Train Management Page - Leo #5 
- [x] Customer Management Page - Johnny #6 
- [x] Log in page - Marshall #7 

@EADG6/gpw-coding  Leave comments if u have any questions

**Comment by MarshallCN** [comment]
for example, u can upload a screenshot in comment after pushing to repository 
* Log in page
![image](https://cloud.githubusercontent.com/assets/16070638/25735850/d00e7ab4-31a0-11e7-8510-8503b81e6ef6.png)

**Comment by MarshallCN** [comment]
* New Customer Page
![image](https://cloud.githubusercontent.com/assets/16070638/25773800/bab0f298-32b6-11e7-8f10-849b65507532.png)
* Customer Management Page
![image](https://cloud.githubusercontent.com/assets/16070638/25773807/e216cf6a-32b6-11e7-9b85-f64516022c5a.png)

**Comment by MarshallCN** [comment]
* Ticket Selling Page
![image](https://cloud.githubusercontent.com/assets/16070638/25773816/fe6e348c-32b6-11e7-8bce-605575a3d509.png)
